### ISSUE TITLE
2024.05.2 breaks my camera

### ISSUE THREAD

**Issue by nomonkeynodeal** [sca075/valetudo_vacuum_camera#140]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

2024.05.2 breaks my camera. Everything works again after rolling back to 2024.05.1.

The cards just say "valetudo invalid calibration, please check your configuration". Two browsers, cleared cache.

I set this up a while ago and barely remember how anything works, much less how to troubleshoot. If anything sticks out, let me know. Otherwise I guess I will just keep this version until the heatdeath of the universe.

### What version of an integration has described problem?

2024.05.2

### What was the last working version of an integration?

2024.05.1

### What vacuum model do you have problems with?

Dreame L10 Pro

### Please firmware installed on your Vacuum.

2023.12.0

### What type of platform you use?

VEMLinux (Virtual Machine) such as Proxmox, VMWare, etc.

### What version of Home Assistant do you use?

latest as of today

### What type of installation are you running?

Home Assistant OS

### Camera's settings.

```yaml
- type: custom:xiaomi-vacuum-map-card
        map_source:
          camera: camera.dreame_l10_2_camera
        calibration_source:
          camera: true
        entity: vacuum.valetudo_l10_2
        vacuum_platform: Hypfer/Valetudo
        tiles:
          - tile_id: battery_level
            entity: vacuum.valetudo_l10_2
            label: Battery
            attribute: battery_level
            icon_source: vacuum.valetudo_l10_2.attributes.battery_icon
            unit: '%'
          - tile_id: fan_speed
            entity: vacuum.valetudo_l10_2
            label: Fan speed
            attribute: fan_speed
            icon: mdi:fan
            translations:
              silent: Silent
              standard: Standard
              medium: Medium
              turbo: Turbo
              auto: Auto
              gentle: Gentle
          - tile_id: filter_left
            label: Filter left
            icon: mdi:air-filter
            unit: h
            multiplier: 0.016666666666666666
            entity: sensor.valetudo_l10_2_main_filter
            precision: 0
            translations: {}
          - tile_id: main_brush_left
            label: Main brush left
            icon: mdi:brush
            unit: h
            multiplier: 0.016666666666666666
            entity: sensor.valetudo_l10_2_main_brush
            precision: 0
            translations: {}
          - tile_id: side_brush_left
            label: Side brush left
            icon: mdi:brush
            unit: h
            multiplier: 0.016666666666666666
            entity: sensor.valetudo_l10_2_right_brush
            precision: 0
            translations: {}
          - tile_id: cleaned_area
            label: Cleaned area
            icon: mdi:texture-box
            unit: m²
            multiplier: 0.0001
            entity: sensor.valetudo_l10_2_current_statistics_area
            precision: 0
            translations: {}
          - tile_id: cleaning_time
            label: Cleaning time
            icon: mdi:timer-sand
            unit: min
            multiplier: 0.016666666666666666
            entity: sensor.valetudo_l10_2_current_statistics_time
            precision: 0
            translations: {}
        icons: []
        map_locked: true
        two_finger_pan: true
        map_modes:
          - template: vacuum_clean_segment
            service_call_schema:
              service: mqtt.publish
              evaluate_data_as_template: false
              service_data:
                topic: valetudo/L10-2/MapSegmentationCapability/clean/set
                payload: >-
                  {"segment_ids": [[selection]], "iterations": [[repeats]],
                  "customOrder": false}   
            predefined_selections:
              - id: '1'
                icon:
                  name: mdi:shower-head
                  x: 3102
                  'y': 2962
                label:
                  text: Office bath
                  x: 3102
                  'y': 2962
                  offset_y: 35
                outline:
                  - - 2980
                    - 2875
                  - - 3225
                    - 2875
                  - - 3225
                    - 3050
                  - - 2980
                    - 3050
              - id: '2'
                icon:
                  name: mdi:shower-head
                  x: 2735
                  'y': 2985
                label:
                  text: Master bath
                  x: 2735
                  'y': 2985
                  offset_y: 35
                outline:
                  - - 2485
                    - 2885
                  - - 2985
                    - 2885
                  - - 2985
                    - 3085
                  - - 2485
                    - 3085
              - id: '4'
                icon:
                  name: mdi:chair-rolling
                  x: 3142
                  'y': 3305
                label:
                  text: Office
                  x: 3142
                  'y': 3305
                  offset_y: 35
                outline:
                  - - 2985
                    - 3055
                  - - 3300
                    - 3055
                  - - 3300
                    - 3555
                  - - 2985
                    - 3555
              - id: '5'
                icon:
                  name: mdi:numeric-3-box
                  x: 2255
                  'y': 3465
                label:
                  text: Hall
                  x: 2255
                  'y': 3465
                  offset_y: 35
                outline:
                  - - 1830
                    - 3335
                  - - 2680
                    - 3335
                  - - 2680
                    - 3595
                  - - 1830
                    - 3595
              - id: '3'
                icon:
                  name: mdi:bed-queen
                  x: 2200
                  'y': 3117
                label:
                  text: Master bed
                  x: 2200
                  'y': 3117
                  offset_y: 35
                outline:
                  - - 2020
                    - 2885
                  - - 2380
                    - 2885
                  - - 2380
                    - 3350
                  - - 2020
                    - 3350
          - name: Zone cleanup
            icon: mdi:select-drag
            run_immediately: false
            coordinates_rounding: true
            coordinates_to_meters_divider: 100
            selection_type: MANUAL_RECTANGLE
            max_selections: 5
            repeats_type: EXTERNAL
            max_repeats: 3
            service_call_schema:
              service: mqtt.publish
              evaluate_data_as_template: true
              service_data:
                topic: valetudo/L10-2/ZoneCleaningCapability/start/set
                payload: >-
                  {"zones": [{%for s in ('[[selection]]')|from_json %}{
                  "points": {"pA": { "x": {{s[0]}}, "y": {{s[1]}} }, "pB": {
                  "x": {{s[2]}}, "y": {{s[1]}} }, "pC": { "x": {{s[2]}}, "y":
                  {{s[3]}} }, "pD": { "x": {{s[0]}}, "y": {{s[3]}} } },
                  "iterations": [[repeats]]}{%if not
                  loop.last%},{%endif%}{%endfor%}]}
            predefined_selections: []
            variables: {}
```
