### ISSUE TITLE
Home Assistant UI hangs / stop responding while the vacuum is running (Rpi 3B+)

### ISSUE THREAD

**Issue by T0ytoy** [sca075/valetudo_vacuum_camera#70]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

When the vacuum is running, even if not displaying the xiaomii-vacuum-card, my Hass instance almost completely hangs: navigating the app is slow, even switch on / off a light with a smart button IRL can take > 20 seconds. If watching the vacuum card, the vacuum position updates but pretty slowly (a few times each minute).

CPU usage is ~30% (one core seem to be maxed out, the 3 others are doing nothing), top indicates that 'python3' process is using 100% CPU.

As soon as the vacuum stops its cycle, everything go back to normal.
I am aware that the Rpi 3B+ is slower than the Rpi4 you are using to test releases, so maybe it is just not enough powerful. That being said it is still weird it maxes out one core and leave nothing to Home Assistant process. 

Would it be possible to execute valetudo vacuum camera computations on another thread? 

I am available to help test things out as much as needed, thank you very much for your hard work!

### What version of an integration has described problem?

v1.5.5

### What vacuum model do you have problems with?

Dreame L10s Ultra

### Please firmware installed on your Vacuum.

3018 with Valetudo 2023.12.0

### What version of Home Assistant do you use?

2024.1.0

### What type of installation are you running?

Home Assistant Container

### Camera's settings.

```yaml
type: custom:xiaomi-vacuum-map-card
entity: vacuum.valetudo_l10su
vacuum_platform: Hypfer/Valetudo
map_source:
  camera: camera.l10s_ultra_camera
calibration_source:
  camera: true
internal_variables:
  topic: valetudo/L10SU
map_modes:
  - template: vacuum_goto
  - template: vacuum_clean_zone
  - template: vacuum_clean_segment
    max_selections: 9
    repeats_type: 3
    selection_type: ROOM
    predefined_selections:
      - id: 2
        label:
          text: Bureau
          x: 3340
          'y': 3200
          offset_y: 15
        icon:
          icon: null
          name: mdi:desk
          x: 3340
          'y': 3200
        outline:
          - - 3197
            - 3037
          - - 3467
            - 3037
          - - 3464
            - 3410
          - - 3196
            - 3410
      - id: 10
        label:
          text: Cuisine
          x: 3640
          'y': 3200
          offset_y: 15
        icon:
          icon: null
          name: mdi:silverware-fork
          x: 3640
          'y': 3200
        outline:
          - - 3467
            - 3041
          - - 3467
            - 3400
          - - 3866
            - 3400
          - - 3870
            - 3041
      - id: 6
        label:
          text: Salon
          x: 4050
          'y': 3150
          offset_y: 15
        icon:
          icon: null
          name: mdi:television-shimmer
          x: 4050
          'y': 3150
        outline:
          - - 3870
            - 3041
          - - 3873
            - 3201
          - - 3848
            - 3201
          - - 3848
            - 3261
          - - 3866
            - 3265
          - - 3866
            - 3400
          - - 4215
            - 3400
          - - 4215
            - 3041
      - id: 1
        label:
          text: Salle d'eau
          x: 3320
          'y': 3480
          offset_y: 15
        icon:
          icon: null
          name: mdi:shower-head
          x: 3320
          'y': 3480
        outline:
          - - 3197
            - 3405
          - - 3467
            - 3407
          - - 3464
            - 3582
          - - 3197
            - 3582
      - id: 12
        label:
          text: Couloir
          x: 3550
          'y': 3690
          offset_y: 15
        icon:
          icon: null
          name: mdi:door
          x: 3550
          'y': 3690
        outline:
          - - 3467
            - 3393
          - - 3467
            - 3767
          - - 3951
            - 3767
          - - 3955
            - 3642
          - - 3571
            - 3642
          - - 3571
            - 3393
      - id: 7
        label:
          text: SdB
          x: 3775
          'y': 3550
          offset_y: 15
        icon:
          icon: null
          name: mdi:shower
          x: 3775
          'y': 3550
        outline:
          - - 3668
            - 3400
          - - 3668
            - 3641
          - - 3853
            - 3641
          - - 3853
            - 3400
      - id: 3
        label:
          text: Chambre
          x: 4000
          'y': 3900
          offset_y: 15
        icon:
          icon: null
          name: mdi:bed
          x: 4000
          'y': 3900
        outline:
          - - 3804
            - 3770
          - - 3804
            - 4072
          - - 4216
            - 4072
          - - 4216
            - 3770
      - id: 8
        label:
          text: ' '
          x: 3905
          'y': 3560
          offset_y: 15
        icon:
          icon: null
          name: mdi:toilet
          x: 3905
          'y': 3560
        outline:
          - - 3860
            - 3495
          - - 3860
            - 3641
          - - 3945
            - 3641
          - - 3945
            - 3495
      - id: 11
        label:
          text: Rangement
          x: 4075
          'y': 3550
          offset_y: 15
        icon:
          icon: null
          name: mdi:bed-empty
          x: 4075
          'y': 3550
        outline:
          - - 3955
            - 3407
          - - 3955
            - 3766
          - - 4216
            - 3766
          - - 4216
            - 3407
    variables:
      topic: valetudo/robot
append_icons: true
icons:
  - type: menu
    menu_id: water_box_mode
    icon_id: water_box_mode
    entity: select.valetudo_l10su_water
    available_values_attribute: options
    icon: mdi:water
    icon_mapping:
      low: mdi:water-minus
      medium: mdi:water
      high: mdi:water-plus
      custom: mdi:water-sync
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        option: '[[value]]'
        entity_id: '[[entity_id]]'
  - type: menu
    menu_id: cleaning_mode
    icon_id: cleaning_mode
    entity: select.valetudo_l10su_mode
    available_values_attribute: options
    icon: mdi:developer-board
    icon_mapping:
      vacuum: mdi:fan
      mop: mdi:water
      vacuum_and_mop: mdi:water-sync
      custom: mdi:water-sync
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        option: '[[value]]'
        entity_id: '[[entity_id]]'
card_mod:
  style: |
    ha-card {
      --map-card-room-outline-fill-color-selected: rgba(130, 130, 130, 0.95);
      --map-card-room-outline-fill-color: rgba(130, 130, 130, 0.6);
      --map-card-room-icon-wrapper-size: 20px;
      --map-card-room-icon-size : 15px;
    }
```
